version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ems-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems_db
      MYSQL_USER: ems_user
      MYSQL_PASSWORD: ems_pass
    ports:
      - "3307:3306" # host:container
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./ems-backend
    container_name: ems-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ems_db
      SPRING_DATASOURCE_USERNAME: ems_user
      SPRING_DATASOURCE_PASSWORD: ems_pass
    ports:
      - "8080:8080"

  frontend:
    build: ./ems-frontend
    container_name: ems-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      # Backend URL for React app
      REACT_APP_API_BASE_URL: http://localhost:8080

volumes:
  mysql_data:
# cp,,po;
